import { useEffect, useMemo, useState } from 'react';
import { FileText, Download, ChevronDown, ChevronUp } from 'lucide-react';
import { supabase } from '../lib/supabase';
import type { Student, Score } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { analyzeStudent, getRiskColor, getCBCColor } from '../lib/riskEngine';
import { generateReportCard, getRiskLabel } from '../lib/reportGenerator';

const TERMS = ['Term 1', 'Term 2', 'Term 3'];

export default function Reports() {
  const { user, profile } = useAuth();

  const [students, setStudents] = useState<Student[]>([]);
  const [scores, setScores] = useState<Score[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTerm, setSelectedTerm] = useState('Term 1');
  const [expandedId, setExpandedId] = useState<string | null>(null);

  useEffect(() => {
    if (!user) return;
    async function load() {
      const [studentsRes, scoresRes] = await Promise.all([
        supabase.from('students').select('*, class:classes(*)').eq('teacher_id', user!.id).order('name'),
        supabase.from('scores').select('*, subject:subjects(*)').eq('teacher_id', user!.id),
      ]);
      setStudents(studentsRes.data ?? []);
      setScores(scoresRes.data ?? []);
      setLoading(false);
    }
    load();
  }, [user]);

  const reports = useMemo(() =>
    students.map(s => {
      const risk = analyzeStudent(s.id, scores);
      return generateReportCard(s, risk, selectedTerm);
    }),
    [students, scores, selectedTerm]
  );

  function printReport(reportId: string) {
    const el = document.getElementById(`report-${reportId}`);
    if (!el) return;
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(`
      <html>
        <head>
          <title>Report Card</title>
          <style>
            body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #0f172a; }
            h1 { font-size: 22px; font-weight: 700; }
            h2 { font-size: 16px; color: #475569; font-weight: 500; margin-top: 4px; }
            .badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: 700; margin-right: 6px; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 24px 0; }
            .cell { padding: 14px; background: #f8fafc; border-radius: 12px; }
            .label { font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px; }
            .value { font-size: 20px; font-weight: 700; color: #0f172a; }
            .comment { background: #f0f9ff; border: 1px solid #bae6fd; padding: 16px; border-radius: 12px; font-size: 14px; line-height: 1.6; color: #0c4a6e; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background: #f8fafc; padding: 10px 14px; text-align: left; font-size: 12px; color: #64748b; font-weight: 600; }
            td { padding: 10px 14px; border-bottom: 1px solid #f1f5f9; font-size: 13px; }
            .school { text-align: center; padding: 20px 0 32px; border-bottom: 2px solid #e2e8f0; margin-bottom: 24px; }
            .school h3 { font-size: 14px; color: #64748b; margin-top: 4px; }
          </style>
        </head>
        <body>
          <div class="school">
            <h1>SANA OS — Student Report Card</h1>
            <h3>Generated by ${profile?.name ?? 'Teacher'} · ${selectedTerm}</h3>
          </div>
          ${el.innerHTML}
        </body>
      </html>
    `);
    w.document.close();
    w.print();
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="w-7 h-7 border-2 border-blue-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Reports</h1>
          <p className="text-slate-500 mt-1">Auto-generated CBC-style report cards</p>
        </div>
        <div>
          <select
            value={selectedTerm}
            onChange={e => setSelectedTerm(e.target.value)}
            className="border border-slate-200 rounded-xl px-3 py-2.5 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            {TERMS.map(t => <option key={t}>{t}</option>)}
          </select>
        </div>
      </div>

      {students.length === 0 ? (
        <div className="bg-white rounded-2xl border border-dashed border-slate-200 p-12 text-center">
          <FileText className="w-10 h-10 text-slate-300 mx-auto mb-3" />
          <p className="font-medium text-slate-600">No reports available</p>
          <p className="text-sm text-slate-400 mt-1">Add students and enter scores to generate reports.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map(report => {
            const colors = getRiskColor(report.risk.riskLevel);
            const isExpanded = expandedId === report.student.id;

            return (
              <div key={report.student.id} className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
                {/* Report header — always visible */}
                <button
                  className="w-full flex items-center gap-4 px-5 py-4 hover:bg-slate-50 transition text-left"
                  onClick={() => setExpandedId(isExpanded ? null : report.student.id)}
                >
                  <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center shrink-0">
                    <span className="font-bold text-blue-700">{report.student.name.charAt(0).toUpperCase()}</span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-semibold text-slate-900">{report.student.name}</p>
                    <p className="text-xs text-slate-400 mt-0.5">
                      {(report.student as any).class?.name ?? 'No class'} · {report.risk.overallAverage}% avg
                    </p>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${colors.badge}`}>
                      {getRiskLabel(report.risk.riskLevel)}
                    </span>
                    <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${getCBCColor(report.risk.cbcLevel)}`}>
                      {report.risk.cbcLevel}
                    </span>
                    {isExpanded ? (
                      <ChevronUp className="w-4 h-4 text-slate-400" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-slate-400" />
                    )}
                  </div>
                </button>

                {/* Expanded report card */}
                {isExpanded && (
                  <div className="border-t border-slate-100">
                    <div id={`report-${report.student.id}`} className="px-6 py-5">
                      {/* Stats row */}
                      <div className="grid grid-cols-3 gap-3 mb-5">
                        <div className="bg-slate-50 rounded-xl p-4">
                          <p className="text-[10px] uppercase tracking-wide text-slate-400 font-medium mb-1">Overall Score</p>
                          <p className="text-2xl font-bold text-slate-900">{report.risk.overallAverage}%</p>
                        </div>
                        <div className="bg-slate-50 rounded-xl p-4">
                          <p className="text-[10px] uppercase tracking-wide text-slate-400 font-medium mb-1">CBC Level</p>
                          <p className={`text-lg font-bold px-2 py-0.5 rounded-lg inline-block ${getCBCColor(report.risk.cbcLevel)}`}>
                            {report.risk.cbcLevel}
                          </p>
                        </div>
                        <div className="bg-slate-50 rounded-xl p-4">
                          <p className="text-[10px] uppercase tracking-wide text-slate-400 font-medium mb-1">Term</p>
                          <p className="text-lg font-bold text-slate-900">{report.term}</p>
                        </div>
                      </div>

                      {/* Subject table */}
                      {report.risk.subjectPerformances.length > 0 && (
                        <div className="mb-5 rounded-xl overflow-hidden border border-slate-100">
                          <table className="w-full text-sm">
                            <thead className="bg-slate-50">
                              <tr>
                                <th className="text-left px-4 py-3 font-semibold text-slate-600 text-xs uppercase tracking-wide">Subject</th>
                                <th className="text-center px-4 py-3 font-semibold text-slate-600 text-xs uppercase tracking-wide">Average</th>
                                <th className="text-center px-4 py-3 font-semibold text-slate-600 text-xs uppercase tracking-wide">CBC</th>
                                <th className="text-center px-4 py-3 font-semibold text-slate-600 text-xs uppercase tracking-wide">Trend</th>
                              </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-50">
                              {report.risk.subjectPerformances.map(sp => (
                                <tr key={sp.subjectId}>
                                  <td className="px-4 py-3 font-medium text-slate-900">{sp.subjectName}</td>
                                  <td className="px-4 py-3 text-center font-semibold text-slate-900">{sp.average}%</td>
                                  <td className="px-4 py-3 text-center">
                                    <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${getCBCColor(sp.cbcLevel)}`}>
                                      {sp.cbcLevel}
                                    </span>
                                  </td>
                                  <td className="px-4 py-3 text-center text-xs capitalize text-slate-500">{sp.trend}</td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      )}

                      {/* Teacher comment */}
                      <div className="bg-blue-50 border border-blue-100 rounded-xl p-4">
                        <p className="text-[10px] uppercase tracking-wide text-blue-400 font-semibold mb-2">Teacher's Comment</p>
                        <p className="text-sm text-slate-700 leading-relaxed italic">"{report.teacherComment}"</p>
                      </div>

                      <p className="text-[10px] text-slate-400 mt-3">
                        Generated: {new Date(report.generatedAt).toLocaleDateString('en-KE', { day: 'numeric', month: 'long', year: 'numeric' })}
                      </p>
                    </div>

                    <div className="px-6 pb-4">
                      <button
                        onClick={() => printReport(report.student.id)}
                        className="flex items-center gap-2 border border-slate-200 hover:border-blue-300 hover:bg-blue-50 text-slate-700 hover:text-blue-700 text-sm font-medium px-4 py-2 rounded-xl transition"
                      >
                        <Download className="w-4 h-4" />
                        Print / Save PDF
                      </button>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
